"""One-shot Omni-Bus device scanner CLI.

Connects to the Translator at TCP 43690, runs `omnibus_bridge.scanner.scan`,
and prints the discovered devices. Optionally writes a YAML file the bridge
can consume as its unit-name source.

Usage:
    python tools/scan.py                            # scan default host
    python tools/scan.py --host 192.0.2.10
    python tools/scan.py --yaml config/units.yaml   # dump to file

**Do not run while OMNIBUS Software is actively uploading/downloading** —
both tools share the 43690 channel.
"""
from __future__ import annotations

import argparse
import asyncio
import logging
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))

from omnibus_bridge.scanner import Device, ScanError, TRANSLATOR, scan  # noqa: E402


def _format_yaml(devices: list[Device]) -> str:
    lines = ["# Generated by tools/scan.py"]
    translators = [d for d in devices if d.device_type == TRANSLATOR]
    others = [d for d in devices if d.device_type != TRANSLATOR]
    if translators:
        t = translators[0]
        lines += [
            "translator:",
            f'  device_id: "{t.device_id}"',
            f'  ip: "{t.ip}"',
            f'  netmask: "{t.netmask}"',
            f'  gateway: "{t.gateway}"',
            f"  port: {t.port}",
        ]
    lines.append("devices:")
    for d in others:
        name = d.name or f"Unit {d.unit_number}"
        safe = name.replace('"', r"\"")
        lines.append(f'  - unit: {d.unit_number}')
        lines.append(f'    name: "{safe}"')
        lines.append(f'    type: {d.device_type}')
    lines.append("")
    return "\n".join(lines)


async def _run(args: argparse.Namespace) -> int:
    try:
        devices = await scan(args.host, args.port, total_timeout=args.timeout)
    except ScanError as e:
        print(f"scan failed: {e}", file=sys.stderr)
        return 1

    print(f"discovered {len(devices)} devices:")
    for d in devices:
        if d.device_type == TRANSLATOR:
            print(f"  Translator  id={d.device_id}  {d.ip}/{d.netmask}  gw={d.gateway}  port={d.port}")
        else:
            name = d.name or "(unnamed)"
            print(f"  unit {d.unit_number:3d}  {d.device_type:18s}  {name}")

    if args.yaml:
        out = Path(args.yaml)
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(_format_yaml(devices))
        print(f"\nwrote {out}")

    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--host", default="192.0.2.10",
                        help="Translator IP (default 192.0.2.10)")
    parser.add_argument("--port", type=int, default=43690)
    parser.add_argument("--timeout", type=float, default=10.0)
    parser.add_argument("--yaml", help="Write discovered devices to this YAML file")
    parser.add_argument("--log-level", default="INFO",
                        choices=["DEBUG", "INFO", "WARNING", "ERROR"])
    args = parser.parse_args()
    logging.basicConfig(
        level=args.log_level,
        format="%(asctime)s %(levelname)-7s %(name)s  %(message)s",
        datefmt="%H:%M:%S",
    )
    return asyncio.run(_run(args))


if __name__ == "__main__":
    raise SystemExit(main())
